* About
This uses N2O and ethylene to form oxadiazole as an example. Basically the steps automated:
- Get PET-MAD
- Relax endpoints (EON+IRA)
- Generate IDPP path (ASE)
- Run ewCI-NEB in EON
- Plot
Conceptually similar to the reproduction done for [1, 2, 5, 6] on Github ([[https://github.com/TheochemUI/gpr_sella_repro][1]], [[https://github.com/HaoZeke/brms_idrot_repro][2]], [[https://github.com/theochemUI/otgpd_repro][5]], [[https://github.com/metatensor/ecosystem-article/tree/main/eon][6]]). We
use ~snakemake~ for this section[fn:: Some of these are inspired by the
workflows of [[https://github.com/amritagos][amritagos]]].

#+caption: DAG for the workflow
[[file:resources/dag.svg]]

Essentially this is as implemented from [3] [[https://github.com/TheochemUI/eOn/pull/77][in EON]] (also [[https://github.com/TheochemUI/eOn/pull/230][here]]) discussed in [4].
** Setup
Everything is part of the repository, but ~eOn~ needs to be installed.
#+begin_src bash
pixi s
#+end_src
*** Development
~git-subrepo~ handles vendored dependencies.
** Usage
#+begin_src bash
pixi s
snakemake -c4 # or c1
# View results/plots/04_plots/cineb.png
#+end_src
For faster experimental visualization is required (compared to editing the ~config/general_config.yaml~) then use ~results~ directly:
#+begin_src bash
cd results/03_neb
python -m rgpycrumbs.cli eon plt_neb --con-file neb.con --plot-structures "crit_points" --facecolor "floralwhite"
#+end_src

** References
#+begin_quote
[1] R. Goswami, M. Masterov, S. Kamath, A. Pena-Torres, and H. Jónsson, “Efficient Implementation of Gaussian Process Regression Accelerated Saddle Point Searches with Application to Molecular Reactions,” J. Chem. Theory Comput., Jul. 2025, doi: 10.1021/acs.jctc.5c00866.

[2] R. Goswami, “Bayesian hierarchical models for quantitative estimates for performance metrics applied to saddle search algorithms,” AIP Adv., vol. 15, no. 8, p. 85210, Aug. 2025, doi: 10.1063/5.0283639.

[3] V. Ásgeirsson et al., “Nudged Elastic Band Method for Molecular Reactions Using Energy-Weighted Springs Combined with Eigenvector Following,” J. Chem. Theory Comput., vol. 17, no. 8, pp. 4929–4945, Aug. 2021, doi: 10.1021/acs.jctc.1c00462.

[4] R. Goswami, “Efficient exploration of chemical kinetics,” Oct. 24, 2025, arXiv: arXiv:2510.21368. doi: 10.48550/arXiv.2510.21368.

[5] R. Goswami and H. Jónsson, “Adaptive pruning for increased robustness and reduced computational overhead in gaussian process accelerated saddle point searches,” Oct. 07, 2025, arXiv: arXiv:2510.06030. doi: 10.48550/arXiv.2510.06030.

[6] F. Bigi et al., “Metatensor and metatomic: foundational libraries for interoperable atomistic machine learning,” Aug. 21, 2025, arXiv: arXiv:2508.15704. doi: 10.48550/arXiv.2508.15704.
#+end_quote

** More visual aids
Re-generate all graphs via:
#+begin_src bash
pixi r all-graphs
#+end_src
*** Filegraph
[[file:resources/filegraph.svg]]
*** Rulegraph
[[file:resources/rulegraph.svg]]
