compute_target: cpu
common:
  number_of_intermediate_imgs: 10
  reactant_file: "resources/reactant.con"
  product_file: "resources/product.con"
paths:
  models: "results/00_models"
  endpoints: "results/01_endpoints"
  idpp: "results/02_idpp"
  neb: "results/03_neb"
  cache: "results/_cache"
eon:
  config: "resources/config.ini"
pet_mad:
  version: "v1.1.0"
