compute_target: cuda
common:
  number_of_intermediate_imgs: 10
systems:
  # ethylene + n2o
  # birkholz -> 01_c2no2
  system_100:
    reactant: resources/ewNEB/configurations/system100-react.xyz
    product: resources/ewNEB/configurations/system100-prod.xyz
    saddle: resources/ewNEB/configurations/system100-sp.xyz
  11_grignard:
    reactant: resources/icFSM/birkholz/11_grignard/initial/ipath_000.con
    product: resources/icFSM/birkholz/11_grignard/initial/ipath_001.con
    saddle: resources/icFSM/birkholz/11_grignard/ts.xyz
  bicyclobutane_05:
    reactant: resources/mlFSM/05_bicyclobutane/initial/ipath_000.con
    product: resources/mlFSM/05_bicyclobutane/initial/ipath_001.con
    saddle: resources/mlFSM/05_bicyclobutane/ts.xyz
paths:
  models: "results/00_models"
  endpoints: "results/01_endpoints"
  neb: "results/02_neb"
  cache: "results/_cache"
eon:
  config: "resources/config.ini"
upet:
  model: "pet-omat-l-v1.0.0"
