# -*- mode:snakemake; -*-
from snakemake.utils import min_version

min_version("6.0")


# Path to config file containing general variables, relative to the workflow folder
configfile: "config/general_config.yml"


def get_all_targets(wildcards):
    targets = []
    if "systems" in config:
        for sys in config["systems"]:
            targets.extend(
                [
                    f"{config['paths']['neb']}/{sys}/results.dat",
                ]
            )
    targets.extend(get_figure_targets(wildcards))
    return targets


def get_figure_targets(wildcards):
    prefix = config["plotting"]["blog_prefix"]
    fig_dir = f"{config['paths']['figures']}/blog"
    return [
        f"{fig_dir}/{prefix}-pipeline.png",
        f"{fig_dir}/{prefix}-1d-path.png",
        f"{fig_dir}/{prefix}-1d-index.png",
        f"{fig_dir}/{prefix}-1d-rmsd.png",
        f"{fig_dir}/{prefix}-2d-cyclo.png",
        f"{fig_dir}/{prefix}-2d-grignard.png",
        f"{fig_dir}/{prefix}-2d-bicyclo.png",
        f"{fig_dir}/{prefix}-convergence.png",
        f"{fig_dir}/{prefix}-force-heatmap.png",
        f"{fig_dir}/{prefix}-sampling-density.png",
        f"{fig_dir}/readcon-v2-summary.csv",
        f"{fig_dir}/stack.json",
    ]

rule all:
    input:
        get_all_targets,
    default_target: True


rule all_figures:
    input:
        get_figure_targets,


module convert_center:
    snakefile:
        "rules/convert_center.smk"
    config:
        config


module get_upet:
    snakefile:
        "rules/get_upet.smk"
    config:
        config


module run_eon:
    snakefile:
        "rules/run_eon.smk"
    config:
        config


module plotting:
    snakefile:
        "rules/plotting.smk"
    config:
        config


use rule * from convert_center as __convert_center_*



use rule * from get_upet


use rule * from run_eon


use rule * from plotting


rule minimize_endpoints:
    input:
        expand(
            f"{config['paths']['endpoints']}/{{endpoint}}_minimized.con",
            endpoint=["reactant", "product"],
        ),
