# -*- mode:snakemake; -*-
from snakemake.utils import min_version

min_version("6.0")


# Path to config file containing general variables, relative to the workflow folder
configfile: "config/general_config.yml"


def get_all_targets(wildcards):
    targets = []
    # Safely access the keys, assuming config is loaded
    if "systems" in config:
        for sys in config["systems"]:
            targets.extend(
                [
                    f"{config['paths']['neb']}/{sys}/results.dat",
                ]
            )
    return targets

rule all:
    input:
        get_all_targets,
    default_target: True


module ira_align:
    snakefile:
        "rules/ira_align.smk"
    config:
        config


module get_upet:
    snakefile:
        "rules/get_upet.smk"
    config:
        config


module run_eon:
    snakefile:
        "rules/run_eon.smk"
    config:
        config


use rule * from ira_align as __ira_align_*



use rule * from get_upet


use rule * from run_eon


rule minimize_endpoints:
    input:
        expand(
            f"{config['paths']['endpoints']}/{{endpoint}}_minimized.con",
            endpoint=["reactant", "product"],
        ),
